server: # REST and WS server
  port: 1710
  address: 0.0.0.0
plugins:
  youtube:
    enabled: true
    oauth:
      enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - MWEB
      - WEBEMBEDDED
      - ANDROID_MUSIC
      - ANDROID_VR
      - TV
      - TVHTML5EMBEDDED
    WEB:
      playback: false
    TVHTML5EMBEDDED:
      playlistLoading: false
      videoLoading: false
      searching: true
    ANDROID_VR:
      searching: false
  lavasrc:
    sources:
      spotify: true
      youtube: false
      flowerytts: true
    spotify:
      clientID: ""
      clientSecret: ""
      countryCode: "VN"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    flowerytts:
      voice: "Alexxander"
      translate: false
      silence: 0
      speed: 1.0
      audioFormat: "mp3"
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"
      snapshot: false # Set to true if you want to use a snapshot version.
#    - dependency: "me.duncte123.java-lyrics-plugin:lavalyrics:1.6.5"
#    - dependency: "me.duncte123:java-lyrics-plugin:1.6.5"
#    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0"
#      snapshot: false
#    - dependency: "group:artifact:version"
#      repository: "repository"
  pluginsDir: "./plugins"
  server:
    password: "thanhz"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
      delay: true
      echo: true
    bufferDurationMs: 2000 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 5 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
      #email: "" # Email of Google account
      #password: "" # Password of Google account
    #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
      #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
      #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
      #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
      #proxyPassword: "" # Password for basic authentication

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000


  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
